### ISSUE TITLE
Can't create items.

### ISSUE THREAD

**Issue by goldenkuky209** [DRE2N/ItemsXL#12]
Hello, everytime i try to create a custom item this message appears:
"An internal error occurred while attempting to perform this command"

**Comment by Sataniel98** [comment]
Please show me the stacktrace.

**Comment by goldenkuky209** [comment]
Custom/items/Mine_Key

# The item type.
# Valid input:
# Caliburn item types
type: "Mine_Key"

# The item material.
# Valid input:
# Caliburn ID of a vanilla item
material: "TRIPWIRE_HOOK"

# A custom display name.
# Valid input:
# Any string; color codes supported.
name: "&6Mine &7Key"

# Custom lore lines.
# Valid input:
# Any string; color codes supported.
lores:
 - "&8Used for entering The Mine."

# Hide flags to hide meta data from the hover description.
# Valid input:
# Bukkit ItemFlag enum name, https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html
itemFlags:
  - "HIDE_ATTRIBUTES"
  - "HIDE_ENCHANTS"

# The item enchantments
# Valid input:
# Bukkit Enchantment enum name as keys, https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
# Any integer as a value
enchantments:
  "PROTECTION_ENVIRONMENTAL": 4
  "THORNS": 1

# The item attribute modifiers
# Valid input:
# Any string as the name
# Bukkit Attribute enum name as the type, https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/attribute/Attribute.html
# Bukkit Operation enum name as the operation, https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/attribute/AttributeModifier.Operation.html
# Slot enum names as the slots
# Any double as the amount

attributes:
  nameOfFirstAttribute:
    type: "GENERIC_ATTACK_DAMAGE"
    slots:
      - "MAIN_HAND"
      - "OFF_HAND"
      - "HEAD"
      - "TORSO"
      - "LEGS"
      - "FEET"
    operation: "ADD_NUMBER"
    amount: 8.5
  nameOfSecondAttribute:
    type: "GENERIC_MOVEMENT_SPEED"
    slots:
      - "OFF_HAND"
    operation: "ADD_NUMBER"
    amount: 8.5

# The damage modifiers for a collection of mobs.
# Valid input:
# Listed CategoryDamageModifier identifiers as keys
# Any double as a value
categoryDamageModifiers:
  category: 2.0

# The damage modifiers for a specific mob species.
# Valid input:
# Caliburn mob IDs as keys
# Any double as a value
mobDamageModifiers:
  50: 0.5

Sent from Mail for Windows 10

**Comment by Sataniel98** [comment]
I still need the stacktrace to see what's wrong.

**Comment by goldenkuky209** [comment]
The stacktrace?

dum., 22 mar. 2020, 17:19 Daniel Saukel <notifications@github.com> a scris:

**Comment by goldenkuky209** [comment]
22.03 08:40:02 [Server] INFO org.bukkit.command.CommandException: Cannot
execute command 'ixl' in plugin ItemsXL v0.5.5 - plugin is disabled.
22.03 08:40:02 [Server] INFO at
org.bukkit.command.PluginCommand.execute(PluginCommand.java:37)
~[patched_1.14.4.jar:git-Paper-239]
22.03 08:40:02 [Server] INFO at
org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
~[patched_1.14.4.jar:git-Paper-239]
22.03 08:40:02 [Server] INFO at
org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
~[patched_1.14.4.jar:git-Paper-239]
22.03 08:40:02 [Server] INFO at
org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701)
~[patched_1.14.4.jar:git-Paper-239]
22.03 08:40:02 [Server] INFO at
net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456)
~[patched_1.14.4.jar:git-Paper-239]
22.03 08:40:02 [Server] INFO at
net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
~[patched_1.14.4.jar:git-Paper-239]
22.03 08:40:02 [Server] INFO at
net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
~[patched_1.14.4.jar:git-Paper-239]
22.03 08:40:02 [Server] INFO at
net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
~[patched_1.14.4.jar:git-Paper-239]
22.03 08:40:02 [Server] INFO at java.lang.Thread.run(Thread.java:748)
[?:1.8.0_222]

dum., 22 mar. 2020, 17:33 goldenkuky <goldenkuky209@gmail.com> a scris:

**Comment by Sataniel98** [comment]
It says "plugin is disabled" - the plugin wasn't loaded successfully. The actual error should be on startup.

**Comment by goldenkuky209** [comment]
I restarted it multiple times and no effect.
But if i delete the cutom item file it works.

dum., 22 mar. 2020, 18:21 Daniel Saukel <notifications@github.com> a scris:

**Comment by goldenkuky209** [comment]
Hello? Are you still here?
I still cant find a solution.

dum., 22 mar. 2020, 18:34 goldenkuky <goldenkuky209@gmail.com> a scris:

**Comment by Sataniel98** [comment]
I'm still waiting for the stacktrace on startup.

**Comment by goldenkuky209** [comment]
[Server] INFO Loading ItemsXL v0.5.5

mar., 24 mar. 2020, 00:53 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
This can't be everything. If the plugin didn't load, it must have had an error while loading.

**Comment by goldenkuky209** [comment]
Do you mind sending me a copy of the file that contains a custom item?

mar., 24 mar. 2020, 15:41 Daniel Saukel <notifications@github.com> a scris:

**Comment by goldenkuky209** [comment]
25.03 13:14:36 [Server] INFO org.bukkit.command.CommandException: Cannot
execute command 'itemsxl' in plugin ItemsXL v0.5.5 - plugin is disabled.

This appears everytime i make a file in
custom > Items and try to use the plugin.

If i delete the file, then the plugin works.
What do i do???

mar., 24 mar. 2020, 20:39 goldenkuky <goldenkuky209@gmail.com> a scris:

**Comment by Sataniel98** [comment]
Again, I need the startup stacktrace. Reading through the file you posted, the first thing I see is that the type is set to something random. Set this to "DEFAULT". It could be that there are other problems that I can't see at the moment.

**Comment by goldenkuky209** [comment]
Where do I find the startup stacktrace?

mie., 25 mar. 2020, 14:27 Daniel Saukel <notifications@github.com> a scris:

**Comment by Sataniel98** [comment]
In the log when the server starts.

**Comment by goldenkuky209** [comment]
5.03 18:24:09 [Server] INFO Enabling ItemsXL v0.5.5
25.03 18:24:09 [Server] INFO [##########[ItemsXL]##########]
25.03 18:24:09 [Server] INFO Internals: [v1_14_R1]
25.03 18:24:09 [Server] INFO Spigot API: [true]
25.03 18:24:09 [Server] INFO Paper API: [true]
25.03 18:24:09 [Server] INFO Economy: [false]
25.03 18:24:09 [Server] INFO Permissions: [false]
25.03 18:24:09 [Server] INFO Metrics: [https://bstats.org/plugin/bukkit/ItemsXL]
25.03 18:24:09 [Server] INFO SpigotMC ID: [14472]
25.03 18:24:09 [Server] INFO [###############################]
25.03 18:24:09 [Server] ERROR Error occurred while enabling ItemsXL v0.5.5 (Is it up to date?)
25.03 18:24:09 [Server] INFO java.lang.NullPointerException: null
25.03 18:24:09 [Server] INFO at de.erethon.itemsxl.ItemsXL.loadItems(ItemsXL.java:193) ~[?:?]
25.03 18:24:09 [Server] INFO at de.erethon.itemsxl.ItemsXL.loadAPI(ItemsXL.java:137) ~[?:?]
25.03 18:24:09 [Server] INFO at de.erethon.itemsxl.ItemsXL.onEnable(ItemsXL.java:68) ~[?:?]

Sent from Mail for Windows 10

**Comment by goldenkuky209** [comment]
Hello, are you still here?

mie., 25 mar. 2020, 19:29 outlook_E3DCDA6D4167E059@outlook.com <
goldenkuky209@gmail.com> a scris:

**Comment by Sataniel98** [comment]
Replace type: "Mine_Key" with type: "DEFAULT"
