### ISSUE TITLE
ItemsXL & CaliburnAPI

### ISSUE THREAD

**Issue by goldenkuky209** [DRE2N/ItemsXL#13]
Do i need CaliburnAPI to use ItemsXL?
If so, how can i instal CaliburnAPI?

**Comment by Sataniel98** [comment]
ItemsXL is an implementation of Caliburn. Caliburn is shaded in the IXL distribution, so you don't need to install anything.

**Comment by goldenkuky209** [comment]
Ok so ItemsXL should work on its own then.
Well, the custom items dont work, i updated ItemsXL and DungeonsXL to the
latest version but it still doesnt work.
It tells me the plugin is disabled whenever i try to add a custom item.

Does DungeonsXL only work with ItemsXL for custom items?

dum., 12 apr. 2020, 18:24 Daniel Saukel <notifications@github.com> a scris:

**Comment by goldenkuky209** [comment]
??

dum., 12 apr. 2020, 19:02 goldenkuky <goldenkuky209@gmail.com> a scris:

**Comment by Sataniel98** [comment]
This is all explained sufficiently in the DXL and IXL/Caliburn wikis. DungeonsXL and ItemsXL both work as they are.
