### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by bobydon1** [DRE2N/ItemsXL#18]
I don't really understand how I make a custom item with this plugin, could you please give me an in-depth explanation of how to make one.

**Comment by Sataniel98** [comment]
Put the item in your hand slot and run /ixl registerItem [ID].

Other than that, you can create a custom item script manually: https://github.com/DRE2N/CaliburnAPI/wiki/custom-items

**Comment by bobydon1** [comment]
by ID you mean the ID if the item?

**Comment by Sataniel98** [comment]
The ID you'd like to assign to the custom item.

**Comment by bobydon1** [comment]
oh ok

**Comment by bobydon1** [comment]
so when I registered the item It created 2 files which do I put what in?
