### ISSUE TITLE
Item slots

### ISSUE THREAD

**Issue by JennaDiamonds** [DRE2N/ItemsXL#2]
in my custom item i have this part of the script
"
attributes:
  nameOfFirstAttribute:
    type: "GENERIC_ARMOR"
    slots:
      - "CHEST"
      - "HEAD"
    operation: "ADD_NUMBER"
    amount: 8.5
"

The CHEST is not showing up in game. I also tried TORSO, BODY and a few other things.. not working. No errors. What am I doing wrong? lol

**Comment by JennaDiamonds** [comment]
Bump :(

**Comment by Sataniel98** [comment]
Nothing wrong with this :) The names from the enum are used, so it's "TORSO".
