### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by ICEconchy** [DRE2N/ItemsXL#3]

**Comment by Sataniel98** [comment]
Oh... kay?

**Comment by ICEconchy** [comment]
http://pastebin.com/sXAiJRYS

Sorry, accidently didn't post error :/

**Comment by Sataniel98** [comment]
Alright, thank you for the report. Is it possible that you didn't add a valid species?

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html

**Comment by ICEconchy** [comment]
I haven't touch the plugin at all?
