### ISSUE TITLE
Black magic text lore line on items recieved via /ixl give

### ISSUE THREAD

**Issue by SlayG** [DRE2N/ItemsXL#4]
I've noticed the line of lore on custom items that consists of black magic text. Is there any way to remove it? And if no, is there any way to change it's contents?

I should also note that it's removable via a 3rd party plugin with no issues, I just want to know if it can be removed/modified in the interest of using the /ixl give command.

**Comment by Sataniel98** [comment]
Hi,
You can remove the ID line with a third party plugin, but IXL won't recognize the item anymore without it. That being said, features like mob / item group based damage modifiers won't work. You can modify the identifier prefix in the config though if you do not want to hide it.
~Regards

**Comment by SlayG** [comment]
I assume that is the identifierprefix line? I've tried to change it, but my changes don't seem to stick. It's always the same line of black magic text.

**Comment by SlayG** [comment]
Checking back in for an update on this, as I said, any changes I make to identifierprefix do not change the line at all.

As a secondary thing, wanted to ask if it would be possible to allow the plugin to read subfolders in the custom items folder? Just for organizational purposes.

Thanks for the help in advance :)

- Slay

**Comment by Sataniel98** [comment]
I haven't tested it but it should also check for files in subfolders.

**Comment by SlayG** [comment]
So about the inability to change the identifier prefix..?
