### ISSUE TITLE
Unable to change IdentifierPrefix line in config

### ISSUE THREAD

**Issue by SlayG** [DRE2N/ItemsXL#5]
Hello,

Any changes to this line are reverted on reboot and/or ignored entirely. It always ends up being the same line of black magic text.

Thanks for your help.

**Comment by Sataniel98** [comment]
Thank you for your report, but I am already aware of it as you already told me so four times within a few days. My studies do not allow me to reproduce and work on Minecraft issues on a regular basis. I have time for it now and again and will eventually fix it.

**Comment by SlayG** [comment]
And every time you simply did not answer, so I apologize for being such a bother.

Thanks.
