### ISSUE TITLE
Random letters in item lore.

### ISSUE THREAD

**Issue by Nikewade** [DRE2N/ItemsXL#6]
How do I get rid of this?
https://gyazo.com/d5d6fb914adadb3fc4fbe2a9a6535ffe
It's the &k letters between combat and coolsword.

**Comment by Sataniel98** [comment]
You don't, that's the ID IXL uses to identify items.

**Comment by Nikewade** [comment]
I know... that's why I closed my issue shortly after making it xD. I would use this plugin but sadly the magic black letters turn me off.

**Comment by Sataniel98** [comment]
Makes it hard to identify items without it as players could just rename them with an anvil. But I need to identify them for the damage matrices. You can change the prefix sothat the ID shows as a white line or however you want it in the main config if that helps.

**Comment by Nikewade** [comment]
When I tried to change the prefix in the config nothing changed.
