### ISSUE TITLE
Serializing Items

### ISSUE THREAD

**Issue by Aeyori** [DRE2N/ItemsXL#9]
So, I'm trying to serialize some mmoitems I have in order to create exclusive drops for dungeons. Whenever I serialize an item what do I do with the serialize.yml because after I serialize another item it disappears. Am I supposed to copy and place it in the custom items folder?

**Comment by Sataniel98** [comment]
Sorry for the late reply.

The serialize command creates a Bukkit YAML representation of an item. You can use this whereever this kind of data is expected, for example in loot tables. The custom items use IXL's own format that is described in the wiki.
